version: "3.8"

services:
  nest-login:
    container_name: nest-login
    restart: always
    depends_on:
      - mongodb
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - nest-login-net

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - nest-login-net
    environment:
      MONGO_INITDB_DATABASE: nest-login

volumes:
  mongo-data:

networks:
  nest-login-net:
